src/App.js, src/components/navBar/NavBar.css, src/pages/home/Home.css
=> chore: alignment fix on navbar

src/pages/checkout/CheckOut.css
made some changes to checkout page
=> chore: alignment fix on checkout page

src/App.js, src/components/navBar/NavBar.jsx, src/components/product/Product.jsx, src/pages/home/Home.jsx, src/pages/productDetails/ProductDetails.jsx, src/pages/products/Products.jsx
i have added the feature of the product the issue is i can access some nested object now will debug those later
=> Oladimeji dev

src/components/navBar/NavBar.jsx
=> chore: upload of home page mobile view

src/App.js, src/components/mobileBar/MobileBar.css, src/components/mobileBar/MobileBar.jsx, src/components/navBar/NavBar.css, src/pages/home/Home.jsx
=> chore: adding mobile navigation

src/components/mobileBar/MobileBar.css, src/components/mobileBar/MobileBar.jsx
=> Funtion page

src/App.js, src/components/navBar/NavBar.jsx, src/pages/specification/Specification.css, src/pages/specification/Specification.jsx
=> chore: added product categories ui

src/pages/specification/SpecHead.jsx, src/pages/specification/Specification.css, src/pages/specification/Specification.jsx, src/pages/specification/lfp/Lfp.jsx, src/pages/specification/ncm/Ncm.jsx
=> chore: added image to product category

src/pages/home/Home.css, src/pages/home/Home.jsx
=> chore: about functionality done

public/index.html
=> chore: testing google tags

src/context.js, src/pages/adminDashboard/AdminDashboard.jsx
=> chore: daily users analysis implemented

public/index.html
=> chore: testing event tracking

public/index.html, src/components/button/Button.jsx, src/pages/register/RegisterPage.jsx
=> chore: event tracking test 2

public/index.html, src/context.js
=> chore: adding google tag manager

src/App.js, src/components/welcome/Welcome.jsx
=> chore: another change

public/index.html
=> chore: real tracking begins

src/pages/adminDashboard/AdminDashboard.css, src/pages/adminDashboard/AdminDashboard.jsx
=> chore: graphical respresentation of this week users

src/pages/adminDashboard/AdminDashboard.jsx
=> chore: corrected bar chart

src/pages/adminDashboard/AdminDashboard.jsx
=> chore: corrected2 bar chart

src/components/footer/Footer.css, src/components/navBar/NavBar.css, src/pages/cart/Cart.css, src/pages/cart/Cart.jsx, src/pages/checkout/CheckOut.css, src/pages/contact/ContactPage.css, src/pages/contact/ContactPage.jsx, src/pages/home/Home.css, src/pages/home/Home.jsx, src/pages/products/Products.css
=> chore: fixing page layout

src/context.js, src/pages/adminDashboard/AdminDashboard.jsx
=> chore: users api added and consumed

src/pages/productDetails/ProductDetails.css, src/pages/productDetails/ProductDetails.jsx
=> chore: fix product details page layout
